import type { SettingsState } from '../SettingsState/SettingsState.ts'

export const createDefaultState = (): SettingsState => {
  return {
    breakPointsExpanded: false,
    breakPointsVisible: true,
    focus: 0,
    id: 1,
    uri: 'test://uri',
    x: 0,
    y: 0,
    width: 800,
    height: 600,
    deltaY: 0,
    itemHeight: 100,
    tabs: [],
    items: [],
    filteredItems: [],
    searchValue: '',
    highlightsEnabled: false,
    preferences: {},
    inputSource: 0,
    filteredItemsCount: 0,
    scrollOffset: 0,
    minLineY: 0,
    maxLineY: 0,
    visibleItems: [],
    history: [],
    historyIndex: -1,
    modifiedSettings: {},
    focusSource: 0,
    scrollBarThumbHeight: 0,
    scrollBarThumbTop: 0,
    scrollBarMinHeight: 20,
    highlightsEnabled: false,
  }
}
