import type { SettingsState } from '../SettingsState/SettingsState.ts'

export const createDefaultState = (): SettingsState => {
  return {
    breakPointsExpanded: false,
    breakPointsVisible: true,
    bottomSpacerHeight: 0,
    checkBoxHeight: 18,
    deltaY: 0,
    filteredItems: [],
    filteredItemsCount: 0,
    focus: 0,
    focusSource: 0,
    height: 600,
    headingFontSize: 14,
    headingPaddingBottom: 8,
    headingPaddingTop: 12,
    highlightsEnabled: false,
    history: [],
    historyIndex: -1,
    id: 1,
    inputBoxHeight: 28,
    inputSource: 0,
    itemHeight: 100,
    items: [],
    labelFontSize: 13,
    maxLineY: 0,
    minContentWidth: 300,
    minLineY: 0,
    modifiedSettings: {},
    preferences: {},
    scrollBarMinHeight: 20,
    scrollBarThumbHeight: 0,
    scrollBarThumbTop: 0,
    scrollOffset: 0,
    searchValue: '',
    selectHeight: 32,
    sideBarMinWidth: 100,
    sideBarWidth: 200,
    tabs: [],
    topSpacerHeight: 0,
    totalContentHeight: 0,
    uri: 'test://uri',
    visibleItems: [],
    visibleSections: [],
    width: 800,
    x: 0,
    y: 0,
  }
}
