import { ClassNames } from '@lvce-editor/virtual-dom-worker'

export const { Viewlet } = ClassNames

export const Settings = 'Settings'
export const SettingsInputWrapper = 'SettingsInputWrapper'
export const InputBox = 'InputBox'
export const SettingsSearchInput = 'SettingsSearchInput'
export const Button = 'Button'
export const InputButton = 'InputButton'
export const SearchFieldButton = 'SearchFieldButton'
export const MaskIcon = 'MaskIcon'
export const MaskIconClearAll = 'MaskIconClearAll'
export const SettingsItem = 'SettingsItem'
export const SettingsItemCheckBox = 'SettingsItemCheckBox'
export const CheckBox = 'CheckBox'
export const Select = 'Select'
export const SettingsItems = 'SettingsItems'
export const SettingsNoResults = 'SettingsNoResults'
export const SettingsMain = 'SettingsMain'
export const SettingsContent = 'SettingsContent'
export const SettingsContentHeading = 'SettingsContentHeading'
export const SettingsHeader = 'SettingsHeader'
export const SettingsSideBar = 'SettingsSideBar'
export const SettingsTabs = 'SettingsTabs'
export const Tab = 'Tab'
export const TabSelected = 'TabSelected'
export const Badge = 'Badge'
export const ModifiedIndicator = 'ModifiedIndicator'
