import { ClassNames } from '@lvce-editor/virtual-dom-worker'

export const {
  CallStackArrow,
  CallStackDescription,
  CallStackLabel,
  Chevron,
  DebugButton,
  DebugButtons,
  DebugPausedMessage,
  DebugPropertyChevron,
  Viewlet,
  DebugPropertyKey,
  DebugRow,
  DebugRowCallStack,
  DebugRowCheckBox,
  DebugRowInputField,
  DebugSectionAction,
  DebugSectionActions,
  DebugSectionHeader,
  DebugValue,
  DebugValueBoolean,
  DebugValueFunction,
  DebugValueGetter,
  DebugValueNumber,
  DebugValueObject,
  DebugValueScopeName,
  DebugValueString,
  DebugValueSymbol,
  DebugValueUndefined,
  DeleteWatchExpression,
  IconButton,
  InputBox,
  InputLabel,
} = ClassNames

export const Settings = 'Settings'
