import type { SettingsState } from '../SettingsState/SettingsState.ts'
import * as SettingsStates from '../SettingsStates/SettingsStates.ts'

export const create = (id: number, uri: string, x: number, y: number, width: number, height: number): void => {
  const state: SettingsState = {
    bottomSpacerHeight: 0,
    breakPointsExpanded: false,
    breakPointsVisible: false,
    checkBoxHeight: 18,
    deltaY: 0,
    filteredItems: [],
    filteredItemsCount: 0,
    focus: 0,
    focusSource: 0,
    headingFontSize: 14,
    headingPaddingBottom: 8,
    headingPaddingTop: 12,
    height,
    highlightsEnabled: false,
    history: [],
    historyIndex: -1,
    id,
    inputBoxHeight: 28,
    inputSource: 0,
    itemHeight: 100,
    items: [],
    labelFontSize: 13,
    maxLineY: 0,
    minContentWidth: 300,
    minLineY: 0,
    modifiedSettings: {},
    preferences: {},
    scrollBarMinHeight: 0,
    scrollBarThumbHeight: 0,
    scrollBarThumbTop: 0,
    scrollOffset: 0,
    searchValue: '',
    selectHeight: 32,
    sideBarMinWidth: 100,
    sideBarWidth: 0,
    tabs: [],
    topSpacerHeight: 0,
    totalContentHeight: 0,
    uri,
    visibleItems: [],
    visibleSections: [],
    width,
    x,
    y,
  }
  SettingsStates.set(id, state, state)
}
